### ISSUE TITLE
Data model for obsidian.yaml not defined

### ISSUE THREAD

**Issue by cmoulliard** [obsidian-toaster/quickstart-catalog#2]
obsidian.yaml file will contain different fields which are not defined :   

Name | Description | Usage | Required | Size
------ | ----------- | -------| ----- | ----
name | Spring Boot Tomcat - Rest  |  Dropdown list of the Front  |  Yes  |  24 chars
description  |  Quickstart to expose a REST Greeting endpoint using SpringBoot and Apache Tomcat in embedded mode   | ?  | Yes  |  255

**Comment by gastaldi** [comment]
The description is displayed below the dropdown list and also as a tooltip when you hover the same combo box

**Comment by cmoulliard** [comment]
I agree but not here within the github repo.

**Comment by gastaldi** [comment]
What do you mean? It's part of obsidian.yml metadata file inside each quickstart

**Comment by cmoulliard** [comment]
I mean that we need also a README markdown/asciidoc page explaining the fields to be included within the YAML file. That should be part of the documentation - Developer Quickstart Guide or something like that
